persistence true
persistence_location /mosquitto/data/

log_dest file /mosquitto/log/mosquitto.log

# TCP MQTT
listener 1883
protocol mqtt
allow_anonymous true

# WebSocket MQTT
listener 8083
protocol websockets
allow_anonymous true

# ORIGINAL CONFIG
#listener 1883
#allow_anonymous true